#goal definition
string mac
string token
nautonomous_mission_msgs/OperationPlan[] operationPlan
---
#result definition
nautonomous_mission_msgs/MissionStatus result
---
#feedback
nautonomous_mission_msgs/MissionStatus feedback
